[2023-05-10 21:00:19,693] {processor.py:153} INFO - Started process (PID=92271) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:00:19,694] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:00:19,694] {logging_mixin.py:115} INFO - [2023-05-10 21:00:19,694] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:00:19,756] {logging_mixin.py:115} INFO - [2023-05-10 21:00:19,756] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:00:19,757] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:00:19,774] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-10 21:00:50,111] {processor.py:153} INFO - Started process (PID=92374) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:00:50,112] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:00:50,112] {logging_mixin.py:115} INFO - [2023-05-10 21:00:50,112] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:00:50,174] {logging_mixin.py:115} INFO - [2023-05-10 21:00:50,173] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:00:50,174] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:00:50,191] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.082 seconds
[2023-05-10 21:01:24,019] {processor.py:153} INFO - Started process (PID=92491) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:01:24,019] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:01:24,020] {logging_mixin.py:115} INFO - [2023-05-10 21:01:24,020] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:01:24,082] {logging_mixin.py:115} INFO - [2023-05-10 21:01:24,081] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:01:24,082] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:01:24,098] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-10 21:01:58,389] {processor.py:153} INFO - Started process (PID=92652) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:01:58,390] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:01:58,390] {logging_mixin.py:115} INFO - [2023-05-10 21:01:58,390] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:01:58,453] {logging_mixin.py:115} INFO - [2023-05-10 21:01:58,452] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:01:58,453] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:01:58,469] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-10 21:02:29,770] {processor.py:153} INFO - Started process (PID=92803) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:02:29,770] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:02:29,771] {logging_mixin.py:115} INFO - [2023-05-10 21:02:29,771] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:02:29,834] {logging_mixin.py:115} INFO - [2023-05-10 21:02:29,834] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:02:29,834] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:02:29,852] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-10 21:03:00,815] {processor.py:153} INFO - Started process (PID=92971) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:03:00,816] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:03:00,816] {logging_mixin.py:115} INFO - [2023-05-10 21:03:00,816] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:03:00,878] {logging_mixin.py:115} INFO - [2023-05-10 21:03:00,878] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:03:00,879] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:03:00,896] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-10 21:03:31,174] {processor.py:153} INFO - Started process (PID=93099) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:03:31,174] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:03:31,175] {logging_mixin.py:115} INFO - [2023-05-10 21:03:31,175] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:03:31,238] {logging_mixin.py:115} INFO - [2023-05-10 21:03:31,237] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:03:31,238] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:03:31,255] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-10 21:04:06,097] {processor.py:153} INFO - Started process (PID=93213) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:04:06,101] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:04:06,102] {logging_mixin.py:115} INFO - [2023-05-10 21:04:06,102] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:04:06,164] {logging_mixin.py:115} INFO - [2023-05-10 21:04:06,164] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:04:06,165] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:04:06,182] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.088 seconds
[2023-05-10 21:04:36,978] {processor.py:153} INFO - Started process (PID=93327) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:04:36,978] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:04:36,979] {logging_mixin.py:115} INFO - [2023-05-10 21:04:36,979] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:04:37,042] {logging_mixin.py:115} INFO - [2023-05-10 21:04:37,042] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:04:37,042] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:04:37,060] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-10 21:05:13,552] {processor.py:153} INFO - Started process (PID=93508) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:05:13,553] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:05:13,554] {logging_mixin.py:115} INFO - [2023-05-10 21:05:13,553] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:05:13,617] {logging_mixin.py:115} INFO - [2023-05-10 21:05:13,617] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:05:13,618] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:05:13,634] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-10 21:05:49,694] {processor.py:153} INFO - Started process (PID=93636) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:05:49,694] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:05:49,695] {logging_mixin.py:115} INFO - [2023-05-10 21:05:49,695] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:05:49,755] {logging_mixin.py:115} INFO - [2023-05-10 21:05:49,755] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:05:49,756] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:05:49,773] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.082 seconds
[2023-05-10 21:06:21,778] {processor.py:153} INFO - Started process (PID=93739) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:06:21,778] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:06:21,779] {logging_mixin.py:115} INFO - [2023-05-10 21:06:21,779] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:06:21,840] {logging_mixin.py:115} INFO - [2023-05-10 21:06:21,839] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:06:21,840] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:06:21,857] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.082 seconds
[2023-05-10 21:06:57,223] {processor.py:153} INFO - Started process (PID=93893) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:06:57,224] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:06:57,224] {logging_mixin.py:115} INFO - [2023-05-10 21:06:57,224] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:06:57,289] {logging_mixin.py:115} INFO - [2023-05-10 21:06:57,288] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:06:57,289] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:06:57,307] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-10 21:07:32,818] {processor.py:153} INFO - Started process (PID=94032) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:07:32,819] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-10 21:07:32,820] {logging_mixin.py:115} INFO - [2023-05-10 21:07:32,820] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:07:32,883] {logging_mixin.py:115} INFO - [2023-05-10 21:07:32,882] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-10 21:07:32,883] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-10 21:07:32,900] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
