[2023-05-15 12:18:34,984] {processor.py:153} INFO - Started process (PID=35362) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:18:34,984] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:18:34,985] {logging_mixin.py:115} INFO - [2023-05-15 12:18:34,985] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:18:35,045] {logging_mixin.py:115} INFO - [2023-05-15 12:18:35,044] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:18:35,045] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:18:35,060] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.078 seconds
[2023-05-15 12:19:14,663] {processor.py:153} INFO - Started process (PID=35689) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:19:14,672] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:19:14,672] {logging_mixin.py:115} INFO - [2023-05-15 12:19:14,672] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:19:14,738] {logging_mixin.py:115} INFO - [2023-05-15 12:19:14,737] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:19:14,738] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:19:14,755] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.095 seconds
[2023-05-15 12:19:45,708] {processor.py:153} INFO - Started process (PID=36035) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:19:45,709] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:19:45,710] {logging_mixin.py:115} INFO - [2023-05-15 12:19:45,709] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:19:45,776] {logging_mixin.py:115} INFO - [2023-05-15 12:19:45,776] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:19:45,776] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:19:45,793] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.088 seconds
[2023-05-15 12:20:19,261] {processor.py:153} INFO - Started process (PID=36237) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:20:19,262] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:20:19,262] {logging_mixin.py:115} INFO - [2023-05-15 12:20:19,262] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:20:19,328] {logging_mixin.py:115} INFO - [2023-05-15 12:20:19,327] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:20:19,328] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:20:19,345] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:20:54,712] {processor.py:153} INFO - Started process (PID=36408) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:20:54,777] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:20:54,778] {logging_mixin.py:115} INFO - [2023-05-15 12:20:54,778] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:20:54,846] {logging_mixin.py:115} INFO - [2023-05-15 12:20:54,846] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:20:54,847] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:20:54,862] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.154 seconds
[2023-05-15 12:21:27,111] {processor.py:153} INFO - Started process (PID=36585) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:21:27,112] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:21:27,112] {logging_mixin.py:115} INFO - [2023-05-15 12:21:27,112] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:21:27,173] {logging_mixin.py:115} INFO - [2023-05-15 12:21:27,173] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:21:27,173] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:21:27,194] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:22:01,255] {processor.py:153} INFO - Started process (PID=36858) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:22:01,256] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:22:01,256] {logging_mixin.py:115} INFO - [2023-05-15 12:22:01,256] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:22:01,320] {logging_mixin.py:115} INFO - [2023-05-15 12:22:01,319] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:22:01,320] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:22:01,340] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.088 seconds
[2023-05-15 12:22:35,500] {processor.py:153} INFO - Started process (PID=37014) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:22:35,501] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:22:35,502] {logging_mixin.py:115} INFO - [2023-05-15 12:22:35,501] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:22:35,565] {logging_mixin.py:115} INFO - [2023-05-15 12:22:35,565] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:22:35,566] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:22:35,581] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:23:09,312] {processor.py:153} INFO - Started process (PID=37166) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:23:09,312] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:23:09,313] {logging_mixin.py:115} INFO - [2023-05-15 12:23:09,313] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:23:09,377] {logging_mixin.py:115} INFO - [2023-05-15 12:23:09,377] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:23:09,378] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:23:09,394] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:23:40,358] {processor.py:153} INFO - Started process (PID=37341) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:23:40,359] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:23:40,359] {logging_mixin.py:115} INFO - [2023-05-15 12:23:40,359] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:23:40,423] {logging_mixin.py:115} INFO - [2023-05-15 12:23:40,423] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:23:40,424] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:23:40,440] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:24:12,706] {processor.py:153} INFO - Started process (PID=37469) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:24:12,707] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:24:12,708] {logging_mixin.py:115} INFO - [2023-05-15 12:24:12,708] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:24:12,771] {logging_mixin.py:115} INFO - [2023-05-15 12:24:12,771] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:24:12,771] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:24:12,788] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:24:47,684] {processor.py:153} INFO - Started process (PID=37664) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:24:47,685] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:24:47,685] {logging_mixin.py:115} INFO - [2023-05-15 12:24:47,685] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:24:47,749] {logging_mixin.py:115} INFO - [2023-05-15 12:24:47,749] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:24:47,750] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:24:47,768] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:25:18,102] {processor.py:153} INFO - Started process (PID=37795) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:25:18,103] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:25:18,104] {logging_mixin.py:115} INFO - [2023-05-15 12:25:18,104] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:25:18,169] {logging_mixin.py:115} INFO - [2023-05-15 12:25:18,168] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:25:18,169] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:25:18,187] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:25:50,455] {processor.py:153} INFO - Started process (PID=37981) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:25:50,456] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:25:50,456] {logging_mixin.py:115} INFO - [2023-05-15 12:25:50,456] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:25:50,522] {logging_mixin.py:115} INFO - [2023-05-15 12:25:50,521] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:25:50,522] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:25:50,538] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:26:23,202] {processor.py:153} INFO - Started process (PID=38141) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:26:23,227] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:26:23,228] {logging_mixin.py:115} INFO - [2023-05-15 12:26:23,228] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:26:23,295] {logging_mixin.py:115} INFO - [2023-05-15 12:26:23,294] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:26:23,295] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:26:23,311] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.112 seconds
[2023-05-15 12:26:57,675] {processor.py:153} INFO - Started process (PID=38304) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:26:57,675] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:26:57,676] {logging_mixin.py:115} INFO - [2023-05-15 12:26:57,676] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:26:57,742] {logging_mixin.py:115} INFO - [2023-05-15 12:26:57,742] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:26:57,742] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:26:57,759] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.088 seconds
[2023-05-15 12:27:31,812] {processor.py:153} INFO - Started process (PID=38563) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:27:31,813] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:27:31,813] {logging_mixin.py:115} INFO - [2023-05-15 12:27:31,813] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:27:31,878] {logging_mixin.py:115} INFO - [2023-05-15 12:27:31,877] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:27:31,878] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:27:31,895] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:28:02,239] {processor.py:153} INFO - Started process (PID=38693) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:28:02,240] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:28:02,240] {logging_mixin.py:115} INFO - [2023-05-15 12:28:02,240] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:28:02,303] {logging_mixin.py:115} INFO - [2023-05-15 12:28:02,303] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:28:02,303] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:28:02,319] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:28:34,420] {processor.py:153} INFO - Started process (PID=38838) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:28:34,421] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:28:34,421] {logging_mixin.py:115} INFO - [2023-05-15 12:28:34,421] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:28:34,488] {logging_mixin.py:115} INFO - [2023-05-15 12:28:34,487] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:28:34,488] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:28:34,504] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:29:10,946] {processor.py:153} INFO - Started process (PID=39060) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:29:10,947] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:29:10,948] {logging_mixin.py:115} INFO - [2023-05-15 12:29:10,948] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:29:11,013] {logging_mixin.py:115} INFO - [2023-05-15 12:29:11,012] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:29:11,013] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:29:11,029] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:29:41,199] {processor.py:153} INFO - Started process (PID=39209) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:29:41,199] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:29:41,200] {logging_mixin.py:115} INFO - [2023-05-15 12:29:41,200] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:29:41,265] {logging_mixin.py:115} INFO - [2023-05-15 12:29:41,264] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:29:41,265] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:29:41,281] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:30:12,483] {processor.py:153} INFO - Started process (PID=39336) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:30:12,501] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:30:12,502] {logging_mixin.py:115} INFO - [2023-05-15 12:30:12,502] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:30:12,569] {logging_mixin.py:115} INFO - [2023-05-15 12:30:12,568] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:30:12,569] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:30:12,586] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.106 seconds
[2023-05-15 12:30:43,463] {processor.py:153} INFO - Started process (PID=39452) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:30:43,464] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:30:43,464] {logging_mixin.py:115} INFO - [2023-05-15 12:30:43,464] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:30:43,529] {logging_mixin.py:115} INFO - [2023-05-15 12:30:43,528] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:30:43,529] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:30:43,545] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:31:18,356] {processor.py:153} INFO - Started process (PID=39588) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:31:18,358] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:31:18,358] {logging_mixin.py:115} INFO - [2023-05-15 12:31:18,358] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:31:18,422] {logging_mixin.py:115} INFO - [2023-05-15 12:31:18,422] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:31:18,422] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:31:18,439] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:31:49,913] {processor.py:153} INFO - Started process (PID=39699) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:31:49,913] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:31:49,914] {logging_mixin.py:115} INFO - [2023-05-15 12:31:49,914] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:31:49,979] {logging_mixin.py:115} INFO - [2023-05-15 12:31:49,978] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:31:49,979] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:31:49,996] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:32:20,891] {processor.py:153} INFO - Started process (PID=39873) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:32:20,892] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:32:20,892] {logging_mixin.py:115} INFO - [2023-05-15 12:32:20,892] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:32:20,957] {logging_mixin.py:115} INFO - [2023-05-15 12:32:20,957] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:32:20,957] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:32:20,974] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:32:57,528] {processor.py:153} INFO - Started process (PID=40027) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:32:57,529] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:32:57,529] {logging_mixin.py:115} INFO - [2023-05-15 12:32:57,529] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:32:57,595] {logging_mixin.py:115} INFO - [2023-05-15 12:32:57,594] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:32:57,595] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:32:57,611] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:33:28,375] {processor.py:153} INFO - Started process (PID=40155) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:33:28,376] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:33:28,377] {logging_mixin.py:115} INFO - [2023-05-15 12:33:28,377] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:33:28,442] {logging_mixin.py:115} INFO - [2023-05-15 12:33:28,441] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:33:28,442] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:33:28,459] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:34:01,696] {processor.py:153} INFO - Started process (PID=40357) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:34:01,697] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:34:01,697] {logging_mixin.py:115} INFO - [2023-05-15 12:34:01,697] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:34:01,762] {logging_mixin.py:115} INFO - [2023-05-15 12:34:01,761] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:34:01,762] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:34:01,779] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:34:35,406] {processor.py:153} INFO - Started process (PID=40510) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:34:35,407] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:34:35,407] {logging_mixin.py:115} INFO - [2023-05-15 12:34:35,407] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:34:35,470] {logging_mixin.py:115} INFO - [2023-05-15 12:34:35,470] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:34:35,471] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:34:35,486] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:35:10,443] {processor.py:153} INFO - Started process (PID=40691) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:35:10,444] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:35:10,445] {logging_mixin.py:115} INFO - [2023-05-15 12:35:10,445] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:35:10,509] {logging_mixin.py:115} INFO - [2023-05-15 12:35:10,509] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:35:10,510] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:35:10,526] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:35:41,858] {processor.py:153} INFO - Started process (PID=40852) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:35:41,859] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:35:41,859] {logging_mixin.py:115} INFO - [2023-05-15 12:35:41,859] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:35:41,925] {logging_mixin.py:115} INFO - [2023-05-15 12:35:41,924] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:35:41,925] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:35:41,942] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:36:13,356] {processor.py:153} INFO - Started process (PID=41025) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:36:13,357] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:36:13,357] {logging_mixin.py:115} INFO - [2023-05-15 12:36:13,357] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:36:13,422] {logging_mixin.py:115} INFO - [2023-05-15 12:36:13,422] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:36:13,423] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:36:13,439] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:36:46,262] {processor.py:153} INFO - Started process (PID=41421) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:36:46,263] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:36:46,263] {logging_mixin.py:115} INFO - [2023-05-15 12:36:46,263] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:36:46,326] {logging_mixin.py:115} INFO - [2023-05-15 12:36:46,326] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:36:46,327] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:36:46,342] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:37:20,279] {processor.py:153} INFO - Started process (PID=41602) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:37:20,280] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:37:20,281] {logging_mixin.py:115} INFO - [2023-05-15 12:37:20,281] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:37:20,346] {logging_mixin.py:115} INFO - [2023-05-15 12:37:20,345] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:37:20,346] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:37:20,362] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:37:52,343] {processor.py:153} INFO - Started process (PID=42099) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:37:52,344] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:37:52,344] {logging_mixin.py:115} INFO - [2023-05-15 12:37:52,344] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:37:52,409] {logging_mixin.py:115} INFO - [2023-05-15 12:37:52,408] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:37:52,409] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:37:52,425] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:38:26,687] {processor.py:153} INFO - Started process (PID=42234) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:38:26,688] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:38:26,688] {logging_mixin.py:115} INFO - [2023-05-15 12:38:26,688] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:38:26,753] {logging_mixin.py:115} INFO - [2023-05-15 12:38:26,752] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:38:26,753] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:38:26,774] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.090 seconds
[2023-05-15 12:39:01,346] {processor.py:153} INFO - Started process (PID=42428) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:39:01,347] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:39:01,348] {logging_mixin.py:115} INFO - [2023-05-15 12:39:01,347] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:39:01,410] {logging_mixin.py:115} INFO - [2023-05-15 12:39:01,410] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:39:01,410] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:39:01,426] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:39:32,707] {processor.py:153} INFO - Started process (PID=42596) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:39:32,708] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:39:32,708] {logging_mixin.py:115} INFO - [2023-05-15 12:39:32,708] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:39:32,773] {logging_mixin.py:115} INFO - [2023-05-15 12:39:32,772] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:39:32,773] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:39:32,789] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:40:02,995] {processor.py:153} INFO - Started process (PID=42778) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:40:03,051] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:40:03,052] {logging_mixin.py:115} INFO - [2023-05-15 12:40:03,051] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:40:03,115] {logging_mixin.py:115} INFO - [2023-05-15 12:40:03,114] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:40:03,115] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:40:03,132] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.139 seconds
[2023-05-15 12:40:35,603] {processor.py:153} INFO - Started process (PID=42918) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:40:35,616] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:40:35,617] {logging_mixin.py:115} INFO - [2023-05-15 12:40:35,617] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:40:35,683] {logging_mixin.py:115} INFO - [2023-05-15 12:40:35,683] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:40:35,684] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:40:35,705] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.105 seconds
[2023-05-15 12:41:08,984] {processor.py:153} INFO - Started process (PID=43073) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:41:09,021] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:41:09,022] {logging_mixin.py:115} INFO - [2023-05-15 12:41:09,022] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:41:09,089] {logging_mixin.py:115} INFO - [2023-05-15 12:41:09,089] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:41:09,090] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:41:09,106] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.125 seconds
[2023-05-15 12:41:43,084] {processor.py:153} INFO - Started process (PID=43259) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:41:43,085] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:41:43,085] {logging_mixin.py:115} INFO - [2023-05-15 12:41:43,085] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:41:43,150] {logging_mixin.py:115} INFO - [2023-05-15 12:41:43,149] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:41:43,150] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:41:43,166] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:42:14,657] {processor.py:153} INFO - Started process (PID=43418) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:42:14,658] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:42:14,659] {logging_mixin.py:115} INFO - [2023-05-15 12:42:14,659] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:42:14,723] {logging_mixin.py:115} INFO - [2023-05-15 12:42:14,722] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:42:14,723] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:42:14,740] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:42:48,093] {processor.py:153} INFO - Started process (PID=43542) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:42:48,093] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:42:48,094] {logging_mixin.py:115} INFO - [2023-05-15 12:42:48,094] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:42:48,159] {logging_mixin.py:115} INFO - [2023-05-15 12:42:48,158] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:42:48,159] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:42:48,176] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:43:21,838] {processor.py:153} INFO - Started process (PID=43713) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:43:21,839] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:43:21,839] {logging_mixin.py:115} INFO - [2023-05-15 12:43:21,839] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:43:21,897] {logging_mixin.py:115} INFO - [2023-05-15 12:43:21,897] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:43:21,897] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:43:21,913] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.078 seconds
[2023-05-15 12:43:56,904] {processor.py:153} INFO - Started process (PID=43915) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:43:56,905] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:43:56,906] {logging_mixin.py:115} INFO - [2023-05-15 12:43:56,906] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:43:56,967] {logging_mixin.py:115} INFO - [2023-05-15 12:43:56,967] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:43:56,968] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:43:56,985] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:44:31,295] {processor.py:153} INFO - Started process (PID=44083) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:44:31,295] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:44:31,296] {logging_mixin.py:115} INFO - [2023-05-15 12:44:31,296] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:44:31,359] {logging_mixin.py:115} INFO - [2023-05-15 12:44:31,359] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:44:31,359] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:44:31,376] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:45:04,426] {processor.py:153} INFO - Started process (PID=44257) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:45:04,427] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:45:04,427] {logging_mixin.py:115} INFO - [2023-05-15 12:45:04,427] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:45:04,490] {logging_mixin.py:115} INFO - [2023-05-15 12:45:04,490] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:45:04,490] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:45:04,508] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:45:37,560] {processor.py:153} INFO - Started process (PID=44414) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:45:37,560] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:45:37,561] {logging_mixin.py:115} INFO - [2023-05-15 12:45:37,561] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:45:37,623] {logging_mixin.py:115} INFO - [2023-05-15 12:45:37,622] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:45:37,623] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:45:37,640] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:46:07,918] {processor.py:153} INFO - Started process (PID=44638) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:46:07,919] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:46:07,920] {logging_mixin.py:115} INFO - [2023-05-15 12:46:07,919] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:46:07,988] {logging_mixin.py:115} INFO - [2023-05-15 12:46:07,988] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:46:07,989] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:46:08,010] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.097 seconds
[2023-05-15 12:46:39,489] {processor.py:153} INFO - Started process (PID=44772) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:46:39,489] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:46:39,490] {logging_mixin.py:115} INFO - [2023-05-15 12:46:39,490] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:46:39,553] {logging_mixin.py:115} INFO - [2023-05-15 12:46:39,553] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:46:39,553] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:46:39,571] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:47:13,739] {processor.py:153} INFO - Started process (PID=44944) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:47:13,740] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:47:13,740] {logging_mixin.py:115} INFO - [2023-05-15 12:47:13,740] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:47:13,802] {logging_mixin.py:115} INFO - [2023-05-15 12:47:13,802] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:47:13,803] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:47:13,820] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:47:48,712] {processor.py:153} INFO - Started process (PID=45088) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:47:48,713] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:47:48,714] {logging_mixin.py:115} INFO - [2023-05-15 12:47:48,713] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:47:48,777] {logging_mixin.py:115} INFO - [2023-05-15 12:47:48,777] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:47:48,778] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:47:48,794] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:48:22,603] {processor.py:153} INFO - Started process (PID=45253) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:48:22,603] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:48:22,604] {logging_mixin.py:115} INFO - [2023-05-15 12:48:22,603] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:48:22,665] {logging_mixin.py:115} INFO - [2023-05-15 12:48:22,664] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:48:22,665] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:48:22,682] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.082 seconds
[2023-05-15 12:48:59,131] {processor.py:153} INFO - Started process (PID=45483) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:48:59,132] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:48:59,132] {logging_mixin.py:115} INFO - [2023-05-15 12:48:59,132] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:48:59,195] {logging_mixin.py:115} INFO - [2023-05-15 12:48:59,194] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:48:59,195] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:48:59,212] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:49:33,163] {processor.py:153} INFO - Started process (PID=45627) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:49:33,164] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:49:33,165] {logging_mixin.py:115} INFO - [2023-05-15 12:49:33,165] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:49:33,228] {logging_mixin.py:115} INFO - [2023-05-15 12:49:33,227] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:49:33,228] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:49:33,246] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:50:04,288] {processor.py:153} INFO - Started process (PID=45783) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:50:04,289] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:50:04,289] {logging_mixin.py:115} INFO - [2023-05-15 12:50:04,289] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:50:04,352] {logging_mixin.py:115} INFO - [2023-05-15 12:50:04,352] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:50:04,352] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:50:04,370] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:50:39,002] {processor.py:153} INFO - Started process (PID=45923) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:50:39,003] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:50:39,004] {logging_mixin.py:115} INFO - [2023-05-15 12:50:39,003] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:50:39,067] {logging_mixin.py:115} INFO - [2023-05-15 12:50:39,067] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:50:39,067] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:50:39,086] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.087 seconds
[2023-05-15 12:51:14,344] {processor.py:153} INFO - Started process (PID=46065) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:51:14,345] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:51:14,345] {logging_mixin.py:115} INFO - [2023-05-15 12:51:14,345] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:51:14,408] {logging_mixin.py:115} INFO - [2023-05-15 12:51:14,407] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:51:14,408] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:51:14,424] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:51:48,332] {processor.py:153} INFO - Started process (PID=46380) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:51:48,333] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:51:48,334] {logging_mixin.py:115} INFO - [2023-05-15 12:51:48,334] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:51:48,405] {logging_mixin.py:115} INFO - [2023-05-15 12:51:48,404] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:51:48,405] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:51:48,425] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.097 seconds
[2023-05-15 12:52:20,314] {processor.py:153} INFO - Started process (PID=46629) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:52:20,314] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:52:20,315] {logging_mixin.py:115} INFO - [2023-05-15 12:52:20,315] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:52:20,374] {logging_mixin.py:115} INFO - [2023-05-15 12:52:20,374] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:52:20,375] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:52:20,392] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.081 seconds
[2023-05-15 12:52:52,284] {processor.py:153} INFO - Started process (PID=46766) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:52:52,284] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:52:52,285] {logging_mixin.py:115} INFO - [2023-05-15 12:52:52,285] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:52:52,348] {logging_mixin.py:115} INFO - [2023-05-15 12:52:52,347] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:52:52,348] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:52:52,365] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:53:23,864] {processor.py:153} INFO - Started process (PID=46910) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:53:23,865] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:53:23,866] {logging_mixin.py:115} INFO - [2023-05-15 12:53:23,866] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:53:23,928] {logging_mixin.py:115} INFO - [2023-05-15 12:53:23,928] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:53:23,929] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:53:23,945] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:53:57,693] {processor.py:153} INFO - Started process (PID=47103) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:53:57,695] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:53:57,696] {logging_mixin.py:115} INFO - [2023-05-15 12:53:57,695] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:53:57,758] {logging_mixin.py:115} INFO - [2023-05-15 12:53:57,758] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:53:57,758] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:53:57,783] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.093 seconds
[2023-05-15 12:54:29,646] {processor.py:153} INFO - Started process (PID=47222) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:54:29,647] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:54:29,648] {logging_mixin.py:115} INFO - [2023-05-15 12:54:29,648] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:54:29,711] {logging_mixin.py:115} INFO - [2023-05-15 12:54:29,711] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:54:29,712] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:54:29,728] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:55:02,894] {processor.py:153} INFO - Started process (PID=47386) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:55:02,895] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:55:02,896] {logging_mixin.py:115} INFO - [2023-05-15 12:55:02,895] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:55:02,957] {logging_mixin.py:115} INFO - [2023-05-15 12:55:02,957] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:55:02,957] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:55:02,975] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.084 seconds
[2023-05-15 12:55:25,160] {processor.py:153} INFO - Started process (PID=47784) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:55:25,161] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:55:25,161] {logging_mixin.py:115} INFO - [2023-05-15 12:55:25,161] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:55:25,222] {logging_mixin.py:115} INFO - [2023-05-15 12:55:25,222] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:55:25,222] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:55:25,238] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.081 seconds
[2023-05-15 12:56:00,322] {processor.py:153} INFO - Started process (PID=48088) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:56:00,323] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:56:00,323] {logging_mixin.py:115} INFO - [2023-05-15 12:56:00,323] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:56:00,384] {logging_mixin.py:115} INFO - [2023-05-15 12:56:00,384] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:56:00,384] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:56:00,401] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.082 seconds
[2023-05-15 12:56:35,338] {processor.py:153} INFO - Started process (PID=48230) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:56:35,339] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:56:35,340] {logging_mixin.py:115} INFO - [2023-05-15 12:56:35,340] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:56:35,402] {logging_mixin.py:115} INFO - [2023-05-15 12:56:35,401] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:56:35,402] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:56:35,418] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:57:08,186] {processor.py:153} INFO - Started process (PID=48559) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:57:08,187] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:57:08,188] {logging_mixin.py:115} INFO - [2023-05-15 12:57:08,188] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:57:08,249] {logging_mixin.py:115} INFO - [2023-05-15 12:57:08,248] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:57:08,249] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:57:08,266] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 12:57:43,744] {processor.py:153} INFO - Started process (PID=48840) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:57:43,745] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:57:43,745] {logging_mixin.py:115} INFO - [2023-05-15 12:57:43,745] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:57:43,808] {logging_mixin.py:115} INFO - [2023-05-15 12:57:43,807] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:57:43,808] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:57:43,826] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.086 seconds
[2023-05-15 12:58:15,384] {processor.py:153} INFO - Started process (PID=49167) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:58:15,385] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:58:15,385] {logging_mixin.py:115} INFO - [2023-05-15 12:58:15,385] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:58:15,446] {logging_mixin.py:115} INFO - [2023-05-15 12:58:15,445] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:58:15,446] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:58:15,462] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.081 seconds
[2023-05-15 12:58:49,999] {processor.py:153} INFO - Started process (PID=49367) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:58:49,999] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:58:50,000] {logging_mixin.py:115} INFO - [2023-05-15 12:58:50,000] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:58:50,057] {logging_mixin.py:115} INFO - [2023-05-15 12:58:50,057] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:58:50,058] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:58:50,075] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.079 seconds
[2023-05-15 12:59:24,859] {processor.py:153} INFO - Started process (PID=49539) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:59:24,860] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:59:24,861] {logging_mixin.py:115} INFO - [2023-05-15 12:59:24,860] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:59:24,923] {logging_mixin.py:115} INFO - [2023-05-15 12:59:24,923] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:59:24,924] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:59:24,941] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 12:59:56,079] {processor.py:153} INFO - Started process (PID=49690) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:59:56,080] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 12:59:56,080] {logging_mixin.py:115} INFO - [2023-05-15 12:59:56,080] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:59:56,142] {logging_mixin.py:115} INFO - [2023-05-15 12:59:56,141] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 12:59:56,142] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 12:59:56,159] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 13:00:27,943] {processor.py:153} INFO - Started process (PID=49930) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:00:27,945] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:00:27,945] {logging_mixin.py:115} INFO - [2023-05-15 13:00:27,945] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:00:28,008] {logging_mixin.py:115} INFO - [2023-05-15 13:00:28,007] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:00:28,008] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:00:28,024] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 13:07:18,326] {processor.py:153} INFO - Started process (PID=51558) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:07:18,326] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:07:18,327] {logging_mixin.py:115} INFO - [2023-05-15 13:07:18,327] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:07:18,377] {logging_mixin.py:115} INFO - [2023-05-15 13:07:18,377] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:07:18,378] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:07:18,391] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.067 seconds
[2023-05-15 13:07:52,494] {processor.py:153} INFO - Started process (PID=51985) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:07:52,509] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:07:52,510] {logging_mixin.py:115} INFO - [2023-05-15 13:07:52,510] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:07:52,574] {logging_mixin.py:115} INFO - [2023-05-15 13:07:52,574] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:07:52,575] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:07:52,591] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.100 seconds
[2023-05-15 13:08:27,611] {processor.py:153} INFO - Started process (PID=52126) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:08:27,612] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:08:27,613] {logging_mixin.py:115} INFO - [2023-05-15 13:08:27,613] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:08:27,676] {logging_mixin.py:115} INFO - [2023-05-15 13:08:27,675] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:08:27,676] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:08:27,693] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.085 seconds
[2023-05-15 13:08:58,544] {processor.py:153} INFO - Started process (PID=52320) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:08:58,545] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:08:58,546] {logging_mixin.py:115} INFO - [2023-05-15 13:08:58,546] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:08:58,608] {logging_mixin.py:115} INFO - [2023-05-15 13:08:58,608] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:08:58,608] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:08:58,624] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 13:09:29,460] {processor.py:153} INFO - Started process (PID=52547) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:09:29,460] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:09:29,461] {logging_mixin.py:115} INFO - [2023-05-15 13:09:29,461] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:09:29,528] {logging_mixin.py:115} INFO - [2023-05-15 13:09:29,527] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:09:29,528] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:09:29,550] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.093 seconds
[2023-05-15 13:10:07,133] {processor.py:153} INFO - Started process (PID=52987) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:10:07,133] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:10:07,134] {logging_mixin.py:115} INFO - [2023-05-15 13:10:07,134] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:10:07,199] {logging_mixin.py:115} INFO - [2023-05-15 13:10:07,198] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:10:07,199] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:10:07,213] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.083 seconds
[2023-05-15 13:10:41,235] {processor.py:153} INFO - Started process (PID=53301) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:10:41,239] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:10:41,240] {logging_mixin.py:115} INFO - [2023-05-15 13:10:41,240] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:10:41,304] {logging_mixin.py:115} INFO - [2023-05-15 13:10:41,304] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:10:41,305] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:10:41,321] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.089 seconds
[2023-05-15 13:14:48,905] {processor.py:153} INFO - Started process (PID=55285) to work on /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:14:48,906] {processor.py:641} INFO - Processing file /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py for tasks to queue
[2023-05-15 13:14:48,906] {logging_mixin.py:115} INFO - [2023-05-15 13:14:48,906] {dagbag.py:507} INFO - Filling up the DagBag from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:14:48,956] {logging_mixin.py:115} INFO - [2023-05-15 13:14:48,955] {dagbag.py:320} ERROR - Failed to import: /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
Traceback (most recent call last):
  File "/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py", line 2, in <module>
    from airflow.providers.amazon.aws.operators.sqs import SQSOperator
ImportError: cannot import name 'SQSOperator' from 'airflow.providers.amazon.aws.operators.sqs' (/home/v/Documents/iac-airflow-dev/dags/venv/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sqs.py)
[2023-05-15 13:14:48,956] {processor.py:653} WARNING - No viable dags retrieved from /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py
[2023-05-15 13:14:48,970] {processor.py:161} INFO - Processing /home/v/Documents/airflowalura/dags/meu_dag_de_sqs.py took 0.066 seconds
